import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");
const [landing, app, css] = await Promise.all([read("app/page.tsx"), read("app/trade/page.tsx"), read("app/globals.css")]);

assert.match(landing, /Liquidation-Free/, "homepage must state the primary product promise");
assert.match(landing, /Leveraged stock tokens, made clear/, "homepage must explain the instrument without redundant exclusivity language");
assert.match(landing, /No forced wallet liquidation/, "homepage must explain the near-zero holder experience");
assert.match(landing, /real reserve collateral/, "homepage must distinguish funded Standby from cosmetic token dust");
assert.match(landing, /Standby does not guarantee recovery/, "homepage must disclose Standby recovery limits");
assert.match(landing, /href="\/trade"/, "homepage must provide an app entry route");
assert.ok(!landing.includes("LevPlay SVM"), "customer-facing brand must be LevPlay");
assert.match(app, /type AppView = "trade" \| "portfolio" \| "history"/, "trade, portfolio and history views must exist");
assert.match(app, /setView\("portfolio"\)/, "successful entry must open the portfolio");
assert.match(app, /setView\("history"\)/, "history must be directly navigable");
assert.match(app, /Open positions \(\{positions\.length\}\)/, "portfolio and history must share a compact activity switcher");
assert.match(app, /pnlPercent\.toFixed\(2\)/, "positions must show unrealized P\/L percentage");
assert.match(app, /paperMode \? "Close"/, "positions must expose a direct close action");
assert.match(app, /setDirection\("Short"\)/, "the audit scope must expose a short position flow");
assert.match(app, /position\.direction === "Long" \? 1 : -1/, "long and short P&L must use opposite signed exposure");
assert.match(app, /Funded Standby floor/, "trade UI must explain the residual-value protection boundary");
assert.match(app, /\[2, 3\]\.map/, "the expanded catalog must expose only 2x and 3x leverage choices");
assert.ok(!app.includes("[2, 3, 5].map"), "5x must not remain selectable");
assert.match(app, /TabsTrigger value="Pre-IPO"/, "pre-IPO references must have a distinct market category");
assert.match(app, /value - exitPosition\.costBasis/, "realized P\/L must include the entry fee");
assert.match(app, /totalValue - totalInvested/, "unrealized P\/L must include the entry fee");
assert.match(app, /const totalDebit = amount \+ fee/, "entry fee must be added on top of chosen position capital");
assert.match(app, /setPaperCash\(paperCash - totalDebit\)/, "paper entry must debit capital plus the entry fee");
assert.match(app, /setPaperCash\(paperCash \+ value\)/, "paper redemption must credit proceeds");
assert.match(app, /balance\.usdc < totalDebit/, "wallet sufficiency must include the entry fee");
assert.match(app, /available \/ \(1 \+ protocol\.feeBps \/ 10_000\)/, "max amount must reserve the fee");
assert.ok(app.includes("Total wallet debit") && app.includes("Fee recipient") && app.includes("Treasury owner"), "review must disclose the full wallet debit and treasury routing");
assert.ok(app.includes("One atomic, wallet-funded") && app.includes("Sign atomic Solana transaction"), "wallet-direct atomic execution must be explicit");
assert.match(app, /setTimeout\(\(\) => setNotice\(null\), 3_000\)/, "feedback must disappear after three seconds");
assert.match(app, /getWallets\(\)/, "wallet discovery must use the Wallet Standard registry");
for (const wallet of ["Phantom", "Backpack", "Jupiter", "Rabby", "OKX Wallet", "Search with WalletConnect"]) assert.ok(app.includes(wallet), `${wallet} must appear in wallet discovery`);
assert.match(app, /Detected on this device/, "installed wallets must be visibly distinguished");
assert.match(app, /Connecting does not approve a trade or move funds/, "wallet selector must explain connection permissions");
assert.match(app, /function AssetLogo/, "market rows and position views must use real asset logos with a safe fallback");
assert.ok(app.includes("Live Solana DEX") && app.includes("Reference offline"), "pre-IPO reference state must distinguish a live display price from an outage");
assert.match(css, /@media\(max-width:800px\)/, "mobile breakpoint must exist");
assert.match(css, /\.app-nav\{position:fixed;left:0;right:0;bottom:0/, "mobile app navigation must remain thumb-accessible");
assert.match(css, /\.position-card\{grid-template-columns:1fr 1fr/, "positions must collapse to a mobile grid");
assert.match(css, /\.history-head\{display:none\}/, "dense table headers must be removed on mobile");
assert.match(css, /\.workspace-tabs\{width:100%\}/, "mobile activity tabs must use the available width");

console.log("LevPlay UI flow: 42 lifecycle, wallet, branding, catalog, Standby disclosure and responsive assertions passed");
